### ISSUE TITLE
[QA] NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by itschenxi** [InternLM/InternLM#148]
### Describe the question.

Hi, I am trying out InternLM, however I am facing an issue, see below. It seems to be a configuration issue, I have tried every effort to uninstall and reinstall dependencies which do not solve the issue, could you tell me how to sort it out? thank you very much.

```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.16s/it]
Traceback (most recent call last):
  File "/root/InternLM/InternLM/run.py", line 3, in <module>
    model = AutoModelForCausalLM.from_pretrained("internlm/internlm-chat-7b",device_map="auto",trust_remote_code=True).half().cuda()
  File "/root/miniconda3/envs/internlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/root/miniconda3/envs/internlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/internlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/internlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/root/miniconda3/envs/internlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 664, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/internlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
NotImplementedError: Cannot copy out of meta tensor; no data!

```

**Comment by itschenxi** [comment]
when I removed the following line everything works fine, can anyone explain why?

device_map="auto"

**Comment by yhcc** [comment]
It seems like that it was caused by the lack of gpu memory.

**Comment by itschenxi** [comment]
I have sorted out by adding an argument torch_dtype=torch.float16
This thread can be closed
