### ISSUE TITLE
按照说明推理的时候报错

### ISSUE THREAD

**Issue by hopeforus** [InternLM/InternLM#17]
>>> model = AutoModelForCausalLM.from_pretrained("/home/hope/work/models/internlm-chat-7b-8k", trust_remote_code=True).to(torch.bfloat16).cuda()
Loading checkpoint shards: 100%|███████████████████████████████| 2/2 [00:11<00:00,  5.90s/it]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'torch' is not defined
>>> import torch
>>> tokenizer = AutoTokenizer.from_pretrained("/home/hope/work/models/internlm-chat-7b-8k", trust_remote_code=True)
>>> model = model.eval()Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'model' is not defined

**Comment by lvhan028** [comment]
PyTorch has to be installed.

**Comment by hopeforus** [comment]
已经安装了 Pytorch == 1.13.1+cu117
(internlm-env) hope@hope-08:~/work/InternLM$ python
Python 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.13.1+cu117'
>>> torch.cuda.is_available()
True
>>>

**Comment by hwang824** [comment]
我在3090上安装运行，也碰到同样的情况

**Comment by hwang824** [comment]
我在3090上安装运行，也碰到同样的情况

**Comment by yhcc** [comment]
应该是由于一开始没有`import torch`，我们会在readme中update一下

**Comment by hopeforus** [comment]
解决了 谢谢
