### ISSUE TITLE
[Bug] After installing the dependency package according to readme and running the training, there was an issue with dependency package error reporting.

### ISSUE THREAD

**Issue by xinlianglalala** [InternLM/InternLM#177]
### Describe the bug

```
_(internlm-env) root@InternLM# torchrun --nnodes=1 --nproc_per_node=8 train.py --config ./configs/7B_sft.py --launcher "torch"
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 82055) of binary: /home/miniconda3/envs/hxl/bin/python
Traceback (most recent call last):
  File "/home/miniconda3/envs/hxl/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1+cu117', 'console_scripts', 'torchrun')())
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED_
------------------------------------------------------------
```

### Environment

(internlm-env) root@:InternLM# pip list
Package                  Version
------------------------ ------------
anykeystore              0.2
apex                     0.1
boto3                    1.28.19
botocore                 1.31.19
certifi                  2023.7.22
cfgv                     3.3.1
charset-normalizer       3.2.0
cmake                    3.27.0
cryptacular              1.6.2
defusedxml               0.7.1
distlib                  0.3.7
dropout-layer-norm       0.1
einops                   0.6.1
exceptiongroup           1.1.2
filelock                 3.12.2
flash-attn               2.0.4
fsspec                   2023.6.0
GPUtil                   1.4.0
greenlet                 2.0.2
huggingface-hub          0.16.4
hupper                   1.12
identify                 2.5.26
idna                     3.4
iniconfig                2.0.0
Jinja2                   3.1.2
jmespath                 1.0.1
lit                      16.0.6
MarkupSafe               2.1.3
mpmath                   1.3.0
networkx                 3.1
ninja                    1.11.1
nodeenv                  1.8.0
numpy                    1.25.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.2
packaging                23.1
PasteDeploy              3.0.1
pbkdf2                   1.3
Pillow                   10.0.0
pip                      23.2.1
plaster                  1.1.2
plaster-pastedeploy      1.0.1
platformdirs             3.10.0
pluggy                   1.2.0
pre-commit               3.3.3
psutil                   5.9.5
pyramid                  2.0.1
pyramid-mailer           0.15.1
pytest                   7.4.0
python-dateutil          2.8.2
python3-openid           3.2.0
PyYAML                   6.0.1
regex                    2023.6.3
repoze.sendmail          4.4.1
requests                 2.31.0
requests-oauthlib        1.3.1
rotary-emb               0.1
s3transfer               0.6.1
sentencepiece            0.1.99
setuptools               68.0.0
six                      1.16.0
SQLAlchemy               2.0.19
sympy                    1.12
tokenizers               0.13.3
tomli                    2.0.1
torch                    1.13.1+cu117
torch-scatter            2.1.1
torchaudio               0.13.1+cu117
torchvision              0.14.1+cu117
tqdm                     4.65.0
transaction              3.1.0
transformers             4.29.2
translationstring        1.4
triton                   2.0.0
typing_extensions        4.7.1
urllib3                  1.26.16
velruse                  1.1.1
venusian                 3.0.0
virtualenv               20.24.2
WebOb                    1.8.7
wheel                    0.38.4
WTForms                  3.0.1
wtforms-recaptcha        0.3.2
xentropy-cuda-lib        0.1
zope.deprecation         5.0
zope.interface           6.0
zope.sqlalchemy          3.0

**Comment by SolenoidWGT** [comment]
perhaps you could try setting `export LD_LIBRARY_PATH=/home/miniconda3/envs/hxl/lib/python3.10/site-packages/torch/lib/:$LD_LIBRARY_PATH` before running python program? It seems to be caused by flashatten not finding the correct torch dynamic lib.

**Comment by xinlianglalala** [comment]
I tried but it doesn't work 
`(internlm-env) root@10-90-43-152:InternLM# export LD_LIBRARY_PATH=/home/miniconda3/envs/hxl/lib/python3.10/site-packages/torch/lib/:$LD_LIBRARY_PATH
(internlm-env) root@10-90-43-152:InternLM# torchrun --nnodes=1 --nproc_per_node=8 train.py --config ./configs/7B_sft.py --launcher "torch"
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
Traceback (most recent call last):
  File "/home/hxl/internlmpck/InternLM/train.py", line 29, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/hxl/internlmpck/InternLM/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/hxl/internlmpck/InternLM/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmbQKV_ as LegacyApplyRotaryEmbQKV_
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import flash_attn_func
  File "/home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 4, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /home/miniconda3/envs/hxl/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
`

**Comment by scenarios** [comment]
Same problems here, I believe it's the issue with rotary_emb. 
can you just try  "import rotary_emb" to see if there is a core dump?

**Comment by xinlianglalala** [comment]
finally I use the docker image to run the task
