### ISSUE TITLE
[Bug] Training got stuck withe different status among GPUs

### ISSUE THREAD

**Issue by tiansiyuan** [InternLM/InternLM#290]
### Describe the bug

Training got stock.

Status of 4 CPUs is in the screenshot.

<img width="680" alt="Screenshot 2023-09-07 at 16 55 25" src="https://github.com/InternLM/InternLM/assets/228619/b17e1359-d547-4f80-b8d4-ae6b8711622d">

### Environment

The environment is set up according to the commands in Dockerfile as I am already in a Docker based environment.

### Other information

Before it stops, it outputs the following:

$ torchrun --nnodes=1 --nproc_per_node=4 train.py --config ./configs/7B_sft.py --launcher "torch"
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
2023-09-07 08:43:09,863 INFO parallel_context.py:508 in set_device -- process rank 0 is bound to host:f363ff97a009 device: 0
2023-09-07 08:43:09,905 INFO parallel_context.py:508 in set_device -- process rank 1 is bound to host:f363ff97a009 device: 1
2023-09-07 08:43:09,909 INFO parallel_context.py:508 in set_device -- process rank 2 is bound to host:f363ff97a009 device: 2
2023-09-07 08:43:09,911 INFO parallel_context.py:508 in set_device -- process rank 3 is bound to host:f363ff97a009 device: 3
2023-09-07 08:43:11,759 INFO parallel_context.py:540 in set_seed -- initialized seed on rank 2, numpy: 1024, python random: 1024, ParallelMode.DATA: 1024, ParallelMode.TENSOR: 1024,the default parallel seed is ParallelMode.DATA.
2023-09-07 08:43:11,759 INFO parallel_context.py:540 in set_seed -- initialized seed on rank 0, numpy: 1024, python random: 1024, ParallelMode.DATA: 1024, ParallelMode.TENSOR: 1024,the default parallel seed is ParallelMode.DATA.
2023-09-07 08:43:11,759 INFO parallel_context.py:540 in set_seed -- initialized seed on rank 1, numpy: 1024, python random: 1024, ParallelMode.DATA: 1024, ParallelMode.TENSOR: 1024,the default parallel seed is ParallelMode.DATA.
2023-09-07 08:43:11,759 INFO launch.py:354 in launch -- Distributed environment is initialized, data parallel size: 4, pipeline parallel size: 1, tensor parallel size: 1
2023-09-07 08:43:11,759 INFO launch.py:80 in args_sanity_check -- gradient_accumulation size will be setted to 4.
2023-09-07 08:43:11,759 INFO launch.py:101 in args_sanity_check -- +++++++++++++++ Data Info +++++++++++++++
2023-09-07 08:43:11,759 INFO launch.py:102 in args_sanity_check -- seq_len: 2048
2023-09-07 08:43:11,759 INFO launch.py:103 in args_sanity_check -- micro_num: 4
2023-09-07 08:43:11,759 INFO launch.py:104 in args_sanity_check -- micro_bsz: 2
2023-09-07 08:43:11,759 INFO launch.py:105 in args_sanity_check -- packed_length: 4096
2023-09-07 08:43:11,759 INFO launch.py:106 in args_sanity_check -- pack_sample_into_one: False
2023-09-07 08:43:11,759 INFO launch.py:107 in args_sanity_check -- min_length: 50
2023-09-07 08:43:11,759 INFO launch.py:108 in args_sanity_check -- valid_micro_num: 4
2023-09-07 08:43:11,759 INFO launch.py:109 in args_sanity_check -- valid_every: 50
2023-09-07 08:43:11,759 INFO launch.py:182 in args_sanity_check -- +++++++++++++++ Ckpt Info +++++++++++++++
2023-09-07 08:43:11,759 INFO launch.py:183 in args_sanity_check -- is enable save ckpt: False
2023-09-07 08:43:11,759 INFO launch.py:184 in args_sanity_check -- save_ckpt_folder: None
2023-09-07 08:43:11,759 INFO launch.py:185 in args_sanity_check -- checkpoint_every: inf
2023-09-07 08:43:11,759 INFO launch.py:186 in args_sanity_check -- load_given_ckpt: False
2023-09-07 08:43:11,759 INFO launch.py:204 in args_sanity_check -- tensorboard_folder: None
2023-09-07 08:43:11,759 INFO launch.py:205 in args_sanity_check -- resume_tb_folder: None
2023-09-07 08:43:11,759 INFO launch.py:213 in args_sanity_check -- +++++++++++++++ Other Info +++++++++++++++
2023-09-07 08:43:11,759 INFO launch.py:214 in args_sanity_check -- cudnn.benchmark: False
2023-09-07 08:43:11,759 INFO launch.py:215 in args_sanity_check -- cudnn.deterministic: False
2023-09-07 08:43:11,759 INFO launch.py:216 in args_sanity_check -- clip_grad_norm: 1.0
2023-09-07 08:43:11,759 INFO launch.py:253 in args_sanity_check -- +++++++++++++++ Model Info +++++++++++++++
2023-09-07 08:43:11,760 INFO launch.py:254 in args_sanity_check -- Model: {'checkpoint': 0, 'num_attention_heads': 32, 'embed_split_hidden': True, 'vocab_size': 103168, 'embed_grad_scale': 1, 'parallel_output': True, 'hidden_size': 4096, 'num_layers': 32, 'mlp_ratio': 2.6666666666666665, 'apply_post_layer_norm': False, 'dtype': torch.float16, 'norm_type': 'rmsnorm', 'layer_norm_epsilon': 1e-05, 'use_flash_attn': True, 'num_chunks': 1}
2023-09-07 08:43:11,760 INFO launch.py:256 in args_sanity_check -- +++++++++++++++ grad_scaler Info +++++++++++++++
2023-09-07 08:43:11,760 INFO launch.py:257 in args_sanity_check -- grad_scaler: {'fp16': {'initial_scale': 65536, 'min_scale': 1, 'growth_interval': 1000}, 'growth_factor': 2, 'backoff_factor': 0.5, 'max_scale': 16777216, 'hysteresis': 2}
2023-09-07 08:43:11,760 INFO launch.py:259 in args_sanity_check -- +++++++++++++++ hybrid_zero_optimizer Info +++++++++++++++
2023-09-07 08:43:11,760 INFO launch.py:260 in args_sanity_check -- hybrid_zero_optimizer: {'overlap_sync_grad': True, 'overlap_sync_param': True, 'reduce_bucket_size': 536870912, 'clip_grad_norm': 1.0}
2023-09-07 08:43:11,760 INFO launch.py:262 in args_sanity_check -- +++++++++++++++ adam Info +++++++++++++++
2023-09-07 08:43:11,760 INFO launch.py:263 in args_sanity_check -- adam: {'lr': 0.0001, 'adam_beta1': 0.9, 'adam_beta2': 0.95, 'adam_beta2_c': 0, 'adam_eps': 1e-08, 'weight_decay': 0.01}
2023-09-07 08:43:11,760 INFO launch.py:265 in args_sanity_check -- +++++++++++++++ beta2_scheduler Info +++++++++++++++
2023-09-07 08:43:11,760 INFO launch.py:266 in args_sanity_check -- beta2_scheduler: {'init_beta2': 0.95, 'c': 0, 'cur_iter': -1}
2023-09-07 08:43:11,760 INFO launch.py:293 in args_sanity_check -- overlap_sync_grad:True, overlap_sync_param:True
Failed to import module uniscale_monitoring. Use default python logger.
2023-09-07 08:43:11,761 INFO modeling_internlm.py:407 in _build_generic_model_1d -- The layer sharding is [[(0, 32)]].
Failed to import module uniscale_monitoring. Use default python logger.Failed to import module uniscale_monitoring. Use default python logger.

2023-09-07 08:43:11,776 INFO parallel_context.py:540 in set_seed -- initialized seed on rank 3, numpy: 1024, python random: 1024, ParallelMode.DATA: 1024, ParallelMode.TENSOR: 1024,the default parallel seed is ParallelMode.DATA.
Failed to import module uniscale_monitoring. Use default python logger.
2023-09-07 08:43:15,032 INFO model_checkpoint.py:321 in __init__ -- load_ckpt_folder will set to :'None'
2023-09-07 08:43:15,032 WARNING model_checkpoint.py:323 in __init__ -- no set stop_file_path, quit_signal_handler is disable
2023-09-07 08:43:56,739 INFO training_internlm.py:257 in get_validation_data_loader -- load validation dataset val with valid batch size 8 and samples 62.
2023-09-07 08:43:56,756 INFO model_checkpoint.py:523 in try_load_model -- ===========New Run Sep07_08-43-11 on host:f363ff97a009,rank=0,tp=0,pp=0,dp=0===========
2023-09-07 08:43:56,762 INFO hybrid_zero_optim.py:291 in _partition_param_list -- Number of elements on ranks: [1839374336, 1888731136, 1866686464, 1727156224], rank:0
2023-09-07 08:44:18,002 INFO writer.py:57 in init_tb_writer -- Login tensorboard logs to: 7b_train/Sep07_08-43-11/tensorboards
2023-09-07 08:44:18,531 INFO gputest.py:129 in bench_gpu -- benchmarking gpu speed ...
2023-09-07 08:44:24,348 WARNING gputest.py:158 in bench_gpu -- Rank 3 GPU is slower than avg, Hostname f363ff97a009, tflops 101.97, avg 109.07, CPU temp 49.0, GPU temp 34.0
2023-09-07 08:44:24,348 WARNING gputest.py:158 in bench_gpu -- Rank 0 GPU is slower than avg, Hostname f363ff97a009, tflops 99.32, avg 109.07, CPU temp 49.0, GPU temp 31.0
2023-09-07 08:44:24,348 INFO gputest.py:91 in bench_net -- benchmarking network speed ...
2023-09-07 08:44:33,025 INFO training_internlm.py:429 in record_current_batch_training_metrics -- tflops=88.4909665848009 step=0 loss=11.643329620361328 tgs (tokens/gpu/second)=1992.53 lr=4.0000000000000003e-07 loss_scale=65536.0 grad_norm={'0_default': 63.77750632080248} micro_num=4 num_consumed_tokens=65536 inf_nan_skip_batches=0 num_samples_in_batch=18 largest_length=2048 largest_batch=6 smallest_batch=3 adam_beta2=0.95 fwd_bwd_time=5.42 acc=0.0 perplexity=112170.0547 acc/en=0.0 acc/cn=0.0 acc/code=0.0 tokens/en=60571 tokens/cn=0 tokens/code=0 loss_from_metric=11.6278 loss/en=11.6278 loss/cn=nan loss/code=nan 
2023-09-07 08:44:35,258 ERROR train.py:308 in <module> -- Raise exception from f363ff97a009 with rank id: 1
Traceback (most recent call last):
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 306, in <module>
    main(args)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 227, in main
    _, _, loss = trainer.execute_schedule(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/trainer.py", line 174, in execute_schedule
    output, label, loss = self._schedule.forward_backward_step(self._engine, data_iter, **kwargs)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 179, in forward_backward_step
    _output, _loss = self._train_one_batch(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 110, in _train_one_batch
    self._call_hooks("post_helper_func", output, label)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 60, in _call_hooks
    getattr(hook, func_name)(self, *args, **kwargs)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/base_scheduler.py", line 187, in post_helper_func
    self._post_func(outputs, label)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/model/metrics.py", line 51, in __call__
    return self.update(logits, labels, type_ids=self.type_ids)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/model/metrics.py", line 134, in update
    sum_exp_logits = torch.exp(shift_logits).sum(dim=-1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.57 GiB (GPU 1; 79.32 GiB total capacity; 73.60 GiB already allocated; 639.56 MiB free; 75.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

2023-09-07 08:44:35,278 ERROR train.py:308 in <module> -- Raise exception from f363ff97a009 with rank id: 2
Traceback (most recent call last):
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 306, in <module>
    main(args)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 227, in main
    _, _, loss = trainer.execute_schedule(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/trainer.py", line 174, in execute_schedule
    output, label, loss = self._schedule.forward_backward_step(self._engine, data_iter, **kwargs)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 179, in forward_backward_step
    _output, _loss = self._train_one_batch(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 110, in _train_one_batch
    self._call_hooks("post_helper_func", output, label)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 60, in _call_hooks
    getattr(hook, func_name)(self, *args, **kwargs)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/base_scheduler.py", line 187, in post_helper_func
    self._post_func(outputs, label)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/model/metrics.py", line 51, in __call__
    return self.update(logits, labels, type_ids=self.type_ids)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/model/metrics.py", line 134, in update
    sum_exp_logits = torch.exp(shift_logits).sum(dim=-1)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.57 GiB (GPU 2; 79.32 GiB total capacity; 73.35 GiB already allocated; 35.56 MiB free; 76.20 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by tiansiyuan** [comment]
Then, timeout:

[E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803457 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803620 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803457 milliseconds before timing out.
2023-09-07 09:14:40,098 ERROR train.py:308 in <module> -- Raise exception from f363ff97a009 with rank id: 3
Traceback (most recent call last):
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 306, in <module>
    main(args)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 227, in main
    _, _, loss = trainer.execute_schedule(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/trainer.py", line 174, in execute_schedule
    output, label, loss = self._schedule.forward_backward_step(self._engine, data_iter, **kwargs)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 179, in forward_backward_step
    _output, _loss = self._train_one_batch(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 121, in _train_one_batch
    engine.backward(loss)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/engine.py", line 145, in backward
    return self.optimizer.backward(loss)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 480, in backward
    loss.backward(retain_graph=retain_graph)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 321, in reduce_grad_hook
    reduction_func()
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 334, in _store_and_try_reduce_grads_by_bucket
    self._reduce_grads_stored_in_bucket(reduce_rank, last_bucket=False)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 354, in _reduce_grads_stored_in_bucket
    self._reduce_grads_by_rank(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 392, in _reduce_grads_by_rank
    self._reduce_and_copy(bucket=param_bucket, reduce_rank=reduce_rank)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 404, in _reduce_and_copy
    reduced_flat = reduce_tensor(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/utils.py", line 116, in reduce_tensor
    dist.all_reduce(tensor_to_reduce, group=group)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1536, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 3.  Original reason for failure was: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803620 milliseconds before timing out.

[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803620 milliseconds before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 312004) of binary: /opt/conda/envs/internlm-env/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/internlm-env/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1+cu117', 'console_scripts', 'torchrun')())
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train.py FAILED
-------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-07_09:14:45
  host      : f363ff97a009
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 312007)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 312007
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-07_09:14:45
  host      : f363ff97a009
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 312004)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 312004
=======================================================

**Comment by tiansiyuan** [comment]
Then, timeout with the following output:

```
[E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803457 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803620 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803457 milliseconds before timing out.
2023-09-07 09:14:40,098 ERROR train.py:308 in <module> -- Raise exception from f363ff97a009 with rank id: 3
Traceback (most recent call last):
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 306, in <module>
    main(args)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/train.py", line 227, in main
    _, _, loss = trainer.execute_schedule(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/trainer.py", line 174, in execute_schedule
    output, label, loss = self._schedule.forward_backward_step(self._engine, data_iter, **kwargs)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 179, in forward_backward_step
    _output, _loss = self._train_one_batch(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/scheduler/no_pipeline_scheduler.py", line 121, in _train_one_batch
    engine.backward(loss)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/core/engine.py", line 145, in backward
    return self.optimizer.backward(loss)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 480, in backward
    loss.backward(retain_graph=retain_graph)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 321, in reduce_grad_hook
    reduction_func()
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 334, in _store_and_try_reduce_grads_by_bucket
    self._reduce_grads_stored_in_bucket(reduce_rank, last_bucket=False)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 354, in _reduce_grads_stored_in_bucket
    self._reduce_grads_by_rank(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 392, in _reduce_grads_by_rank
    self._reduce_and_copy(bucket=param_bucket, reduce_rank=reduce_rank)
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/hybrid_zero_optim.py", line 404, in _reduce_and_copy
    reduced_flat = reduce_tensor(
  File "/home/jovyan/work/workspace/tiansiyuan/InternLM/internlm/solver/optimizer/utils.py", line 116, in reduce_tensor
    dist.all_reduce(tensor_to_reduce, group=group)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1536, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 3.  Original reason for failure was: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803620 milliseconds before timing out.

[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=316, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1803620 milliseconds before timing out.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 312004) of binary: /opt/conda/envs/internlm-env/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/internlm-env/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1+cu117', 'console_scripts', 'torchrun')())
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/internlm-env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=======================================================
train.py FAILED
-------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-07_09:14:45
  host      : f363ff97a009
  rank      : 3 (local_rank: 3)
  exitcode  : -6 (pid: 312007)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 312007
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-07_09:14:45
  host      : f363ff97a009
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 312004)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 312004
=======================================================
```

**Comment by heroes999** [comment]
@tiansiyuan have you solved the problem? I've encountered a similar one.

**Comment by tiansiyuan** [comment]
> @tiansiyuan have you solved the problem? I've encountered a similar one.

Nope

**Comment by Adenialzz** [comment]
Maybe loss=nan caused this timeout error? I encounter the same error with loss = nan, and I am trying to fix this. Have you made any progress?

**Comment by tiansiyuan** [comment]
No. My environment is gone, unfortunately.
