### ISSUE TITLE
[Bug] OSError: Cannot find empty port in range: 6006-6006. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

### ISSUE THREAD

**Issue by ZhengHui-Z** [InternLM/InternLM#356]
### Describe the bug

ERROR:    [Errno 99] error while attempting to bind on address ('::1', 6006, 0, 0): cannot assign requested address
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 541, in <module>
    fire.Fire(run)
  File "/home/user/anaconda3/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/anaconda3/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/anaconda3/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/user/anaconda3/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 536, in run
    run_local(model_path_or_server, server_name, server_port, batch_size,
  File "/home/user/anaconda3/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 500, in run_local
    demo.queue(concurrency_count=batch_size, max_size=100,
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1843, in launch
    ) = networking.start_server(
  File "/home/user/anaconda3/lib/python3.10/site-packages/gradio/networking.py", line 169, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 6006-6006. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

_No response_

模型信息：
模型：internlm-chat-20b
转换指令：python3 -m lmdeploy.serve.turbomind.deploy internlm-chat-20b /data/model/internlm-chat-20b

启动方式：

```
python3 -m lmdeploy.serve.gradio.app ./workspace --server_port 10020
```

**Comment by ZhengHui-Z** [comment]
加上--server_name可以正常启动

**Comment by JerryCohen22** [comment]
> 加上--server_name可以正常启动

您好，请问最终是输入哪行命令可以正常启动呀，我这边也碰到了一样的问题

**Comment by oppppphjj** [comment]
你运行的python文件里应该含有一个
`    demo.queue().launch(
        share=False,
        inbrowser=True,
        server_port=9001,
        server_name="192.168.1.193",
    )`
    这样的一个函数调用
    你需要修改一些这几个传入参数，因为这几个参数是你web服务器的端口监听设置，基本上是更改server_port和server_name就可以了，然后python xxx.py 运行这个python文件就可以了
