### ISSUE TITLE
[Bug] transformers latest 4.34.0, AttributeError: 'InternLMTokenizer' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by vansin** [InternLM/InternLM#400]
### Describe the bug

````shell
>>> from transformers import AutoTokenizer, AutoModelForCausalLM
>>> tokenizer = AutoTokenizer.from_pretrained("internlm/internlm-chat-7b", trust_remote_code=True)
````

```shell
>>> tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/internlm-chat-7b", trust_remote_code=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-chat-7b/tokenization_internlm.py", line 68, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-chat-7b/tokenization_internlm.py", line 108, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-chat-7b/tokenization_internlm.py", line 96, in vocab_size
    return self.sp_model.get_piece_size()
AttributeError: 'InternLMTokenizer' object has no attribute 'sp_model'
>>> tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/internlm-chat-7b", trust_remote_code=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-chat-7b/tokenization_internlm.py", line 68, in __init__
    super().__init__(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-chat-7b/tokenization_internlm.py", line 108, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-chat-7b/tokenization_internlm.py", line 96, in vocab_size
    return self.sp_model.get_piece_size()
AttributeError: 'InternLMTokenizer' object has no attribute 'sp_model'
```

### Environment
```shell
transformers==4.34.0
```

when version==4.33.3 is fine

![image](https://github.com/InternLM/InternLM/assets/25839884/804b40ba-0e5d-4081-9b5a-a1a03dbec41b)

**Comment by AllentDan** [comment]
https://github.com/huggingface/transformers/issues/26340#issuecomment-1733371279

**Comment by KnutJaegersberg** [comment]
I can use the model and fine-tune it in autotrain-advanced with a modified tokenization_internlm.py. moved super().__init__() to a line after the creation of self.sp_model in tokenization_internlm.py
However, fine-tuning seems to finish early or the time estimate is just totally off.

**Comment by KnutJaegersberg** [comment]
Here is my adjusted file:

https://huggingface.co/KnutJaegersberg/deacon-20b-gptq/blob/main/tokenization_internlm.py

**Comment by AllentDan** [comment]
@KnutJaegersberg Moving `super().init()` is not supposed to influence anything.

**Comment by KnutJaegersberg** [comment]
Got it, I just share what I did :)

**Comment by x54-729** [comment]
This bug has been already fixed by moving super.__init__() to the last line of `InternlmLM.__init__`
See: https://huggingface.co/internlm/internlm-chat-7b/blob/main/tokenization_internlm.py
Later I will create a PR to update our tokenizer file
