### ISSUE TITLE
[Bug] 如何正确安装apex和flash-attention?

### ISSUE THREAD

**Issue by surviveMiao** [InternLM/InternLM#437]
### Describe the bug

源代码中apex和flash-attation文件夹下为空，并没有setup.py文件。从教程中的代码中找到相应的文件复制到对应目录中，运行python setup.py install文件却报错。
![image](https://github.com/InternLM/InternLM/assets/96619920/5b7d5a67-536c-4cf5-ab97-54754b884b64)
报错信息如下：
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miaobr/InternLM/InternLM-main/third_party/flash-attention/setup.py", line 163, in <module>
    setup(
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/command/install.py", line 80, in run
    self.do_egg_install()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/command/install.py", line 129, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/miaobr/InternLM/internlm_env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

### Environment

python3.10
torch                     1.13.1+cu117
torch-scatter             2.1.2
torchaudio                0.13.1+cu117
torchvision               0.14.1+cu117

**Comment by gaoyang07** [comment]
git submodule init

**Comment by gaoyang07** [comment]
Hi there, you can check https://internlm.readthedocs.io/zh-cn/latest/?badge=latest for details.
