### ISSUE TITLE
[QA] config.py中的model参数中的 use_flash_attn设置为False,报错

### ISSUE THREAD

**Issue by zhangjunyi111** [InternLM/InternLM#572]
### Describe the question.

Traceback (most recent call last):
  File "train.py", line 303, in <module>
    main(args)
  File "train.py", line 197, in main
    empty_cache_and_diag(batch_count, interval=gpc.config.data.empty_cache_and_diag_interval)
  File "/home/huawei/workspace/shiyan/InternLM-main/internlm/utils/gputest.py", line 40, in empty_cache_and_diag
    bench_gpu()
  File "/home/huawei/workspace/shiyan/InternLM-main/internlm/utils/gputest.py", line 237, in bench_gpu
    time_f = benchmark_forward(inner_attn, qkv)
  File "/home/huawei/workspace/shiyan/InternLM-main/internlm/utils/gputest.py", line 65, in benchmark_forward
    used_time = bench_timer.timeit(repeats)
  File "/home/huawei/.local/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 266, in timeit
    self._timeit(number=max(int(number // 100), 2))
  File "/home/huawei/.local/lib/python3.8/site-packages/torch/utils/benchmark/utils/timer.py", line 256, in _timeit
    return max(self._timer.timeit(number), 1e-9)
  File "/usr/lib/python3.8/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/home/huawei/workspace/shiyan/InternLM-main/internlm/utils/gputest.py", line 58, in amp_wrapper
    test_fn(*inputs, **kwinputs)
  File "/home/huawei/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/huawei/.local/lib/python3.8/site-packages/flash_attn/modules/mha.py", line 100, in forward
    output = flash_attn_unpadded_qkvpacked_func(
  File "/home/huawei/.local/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py", line 256, in flash_attn_unpadded_qkvpacked_func
    return FlashAttnQKVPackedFunc.apply(qkv, cu_seqlens, max_seqlen, dropout_p, softmax_scale,
  File "/home/huawei/.local/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py", line 58, in forward
    out, softmax_lse, rng_state, S_dmask = _flash_attn_forward(
  File "/home/huawei/.local/lib/python3.8/site-packages/flash_attn/flash_attn_interface.py", line 21, in _flash_attn_forward
    softmax_lse, rng_state, *rest = flash_attn_cuda.fwd(
RuntimeError: Expected is_sm90 || is_sm8x || is_sm75 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

**Comment by yingtongxiong** [comment]
Please double check your GPU architecture. You can see [this](https://github.com/Dao-AILab/flash-attention/issues/292).

**Comment by yingtongxiong** [comment]
这里有两个地方可能需要你double check一下。首先是 use_flash_attn这个参数如果被设置为False的话，应该是不会调用到flash自己的cuda函数；然后这个问题出现的原因可以看看[这个](https://github.com/Dao-AILab/flash-attention/issues/292)。

**Comment by zhangjunyi111** [comment]
https://github.com/InternLM/InternLM/issues/511 这里好像你说还有其他算子对flash_attn的调用。这个设置Model的use_flash_attn能控制的住吗？

**Comment by zhangjunyi111** [comment]
如果控制不住，我们的实验室环境是Tesla V100-PCIE. 
![image](https://github.com/InternLM/InternLM/assets/67990935/1b533dea-a2ae-4e14-a6e9-d6600d8cdfc7)
需要怎么做才好？

**Comment by zhangjunyi111** [comment]
@yingtongxiong

**Comment by zhangjunyi111** [comment]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from internlm.model.loss import FlashGPTLMLoss
  File "/home/huawei/workspace/shiyan/InternLM-main/internlm/model/__init__.py", line 4, in <module>
    from .embedding import Embedding1D, RotaryEmbedding
  File "/home/huawei/workspace/shiyan/InternLM-main/internlm/model/embedding.py", line 10, in <module>
    from flash_attn.layers.rotary import ApplyRotaryEmb as LegacyApplyRotaryEmb
ModuleNotFoundError: No module named 'flash_attn'

我把flash_attn卸载掉后，然后将配置文件中model参数的flash_atten的禁用。发现在 embedding.py中有引用这个包。

**Comment by zhangjunyi111** [comment]
![image](https://github.com/InternLM/InternLM/assets/67990935/7901e718-516b-478d-b311-4d6b44d8ce9a)

**Comment by zhangjunyi111** [comment]
![image](https://github.com/InternLM/InternLM/assets/67990935/76f7b6de-75a3-45f5-a68d-782e595561b4)

**Comment by yingtongxiong** [comment]
我们config中的use_flash_attn仅仅是用于控制model训练过程中的attention计算是否使用flash_attn。然后model中其他地方比如rotary embedding，parallelLinear这些都是用的flash_attn，目前这一块暂时还无法支持非flash_attn。

**Comment by zhangjunyi111** [comment]
所以说你们的项目，没有考虑v100，这样子吗？

**Comment by yingtongxiong** [comment]
目前还是受flash_attn项目影响的。但我们未来可能会考虑去针对像rotary，parallelLinear这种去做非flash_attn的适配。

**Comment by zhangjunyi111** [comment]
还有一点疑问，仔细想了一下。好像我们的日志显示已经开始打印loss了，说明进入到训练阶段了把，除了attention层的计算控制，是不是其他层（forward层）没控制导致的？

**Comment by yingtongxiong** [comment]
开始打印loss说明进入了训练阶段，你是把use_flash_attn设置为False了嘛？

**Comment by zhangjunyi111** [comment]
是的

**Comment by zhangjunyi111** [comment]
这个是日志

**Comment by yingtongxiong** [comment]
你的dtype是什么？

**Comment by yingtongxiong** [comment]
你的model config里面的model dtype是多少

**Comment by zhangjunyi111** [comment]
好的。config的model 参数配置如下：
   
    model = dict(
    checkpoint=False,  # The proportion of layers for activation aheckpointing, the optional value are True/False/[0-1]
    num_attention_heads=NUM_ATTENTION_HEAD,
    embed_split_hidden=True,
    vocab_size=VOCAB_SIZE,
    embed_grad_scale=1,
    parallel_output=True,
    hidden_size=HIDDEN_SIZE,
    num_layers=NUM_LAYER,
    mlp_ratio=MLP_RATIO,
    apply_post_layer_norm=False,
    dtype="torch.bfloat16",  # Support: "torch.float16", "torch.half", "torch.bfloat16", "torch.float32", "torch.tf32"
    norm_type="rmsnorm",
    layer_norm_epsilon=1e-5,
    use_flash_attn=False,
    num_chunks=1,  # if num_chunks > 1, interleaved pipeline scheduler is used.
)

**Comment by yingtongxiong** [comment]
那我猜测可能是flash_attn里面的其他算子比如parallelLinear可以支持volta架构的GPU吧？你可以debug一下看看像linear这种会不会调用到flash_attn的linear。

**Comment by zhangjunyi111** [comment]
好的，这边看看，感谢你的建议。另外我们这边将精度调整了下，调到了torch.float16
