### ISSUE TITLE
[Bug] AttributeError: 'InternLMConfig' object has no attribute 'rotary'

### ISSUE THREAD

**Issue by liu00222** [InternLM/InternLM#578]
### Describe the bug

上个星期（1/5/2024）还可以正常load模型做inference的，conda env没有改过，今天再跑就得到了如下错误：
```
Traceback (most recent call last):
  File "/home/....../main.py", line 57, in <module>
    model = IE.create_model(config=model_config)
  File "/home/....../models/__init__.py", line 25, in create_model
    model = Internlm(config)
  File "/home/....../models/Internlm.py", line 12, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(self.name, trust_remote_code=True,
  File "/home/yl764/miniconda3/envs/review/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "/home/yl764/miniconda3/envs/review/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/yl764/.cache/huggingface/modules/transformers_modules/internlm/internlm-chat-7b/84abffb035b4c061fe69f021e5d519983294baba/modeling_internlm.py", line 715, in __init__
    self.model = InternLMModel(config)
  File "/home/yl764/.cache/huggingface/modules/transformers_modules/internlm/internlm-chat-7b/84abffb035b4c061fe69f021e5d519983294baba/modeling_internlm.py", line 544, in __init__
    self.layers = nn.ModuleList([InternLMDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "/home/yl764/.cache/huggingface/modules/transformers_modules/internlm/internlm-chat-7b/84abffb035b4c061fe69f021e5d519983294baba/modeling_internlm.py", line 544, in <listcomp>
    self.layers = nn.ModuleList([InternLMDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "/home/yl764/.cache/huggingface/modules/transformers_modules/internlm/internlm-chat-7b/84abffb035b4c061fe69f021e5d519983294baba/modeling_internlm.py", line 365, in __init__
    self.self_attn = InternLMAttention(config=config)
  File "/home/yl764/.cache/huggingface/modules/transformers_modules/internlm/internlm-chat-7b/84abffb035b4c061fe69f021e5d519983294baba/modeling_internlm.py", line 275, in __init__
    self.rotary_emb = self._init_rope()
  File "/home/yl764/.cache/huggingface/modules/transformers_modules/internlm/internlm-chat-7b/84abffb035b4c061fe69f021e5d519983294baba/modeling_internlm.py", line 278, in _init_rope
    if self.config.rotary["type"] == "origin":
  File "/home/yl764/miniconda3/envs/xxx/lib/python3.9/site-packages/transformers/configuration_utils.py", line 261, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'InternLMConfig' object has no attribute 'rotary'
```
(update) 我看到huggingface上已经有人post了：https://huggingface.co/internlm/internlm-chat-7b/discussions/8
应该就是昨天的一个commit删掉了rotary那行导致了错误。

### Environment
python==3.9
transformers==4.30.2

**Comment by KMnO4-zx** [comment]
我也遇到了同样的问题。我的transformers和torch版本如下：

Name: transformers  Version: 4.35.2
Name: torch   Version: 2.0.1

**Comment by zhangjunyi111** [comment]
应该需要编译安装flash_attn，那个third_part，和apex一个文件夹的那个软件

**Comment by liu00222** [comment]
> 我也遇到了同样的问题。我的transformers和torch版本如下：
> 
> python 3.10 Name: transformers Version: 4.35.2 Name: torch Version: 2.0.1

看这个post：https://huggingface.co/internlm/internlm-chat-7b/discussions/8

手动改cache里的config.json可以解决

**Comment by KMnO4-zx** [comment]
> > 我也遇到了同样的问题。我的transformers和torch版本如下：
> > 
> > python 3.10 Name: transformers Version: 4.35.2 Name: torch Version: 2.0.1
> 
> 看这个post：https://huggingface.co/internlm/internlm-chat-7b/discussions/8
> 
> 手动改cache里的config.json可以解决

好的，感谢您的帮助~
