### ISSUE TITLE
[Bug] `no module named tools` returned from running `web_demo` 

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/InternLM#630]
### Describe the bug

```
(longtextnew) [zhulin1@SH-IDC1-10-140-0-187 InternLM]$ streamlit run ./chat/web_demo.py
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
  Git integration is disabled.
  Streamlit requires Git 2.7.0 or later, but you have [1.8.3.1](http://1.8.3.1/).
  Git is used by Streamlit Cloud (https://streamlit.io/cloud).
  To enable this feature, please update Git.
2024-01-17 10:14:11.287 Did not auto detect external IP.
Please go to https://docs.streamlit.io/ for debugging hints.
  You can now view your Streamlit app in your browser.
  Network URL: http://10.140.0.187:8501/
2024-01-17 10:14:15.532 Uncaught app exception
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/longtextnew/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/zhulin1/InternLM/chat/web_demo.py", line 17, in <module>
    from tools.transformers.interface import GenerationConfig, generate_interactive
ModuleNotFoundError: No module named 'tools'
2024-01-17 10:14:15.924 Uncaught app exception
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/longtextnew/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/zhulin1/InternLM/chat/web_demo.py", line 17, in <module>
    from tools.transformers.interface import GenerationConfig, generate_interactive
ModuleNotFoundError: No module named 'tools'
```

### Environment

```
```

**Comment by ZwwWayne** [comment]
Fixed in https://github.com/InternLM/InternLM/pull/624. Close this issue as completed.
