### ISSUE TITLE
[QA] transformers库版本的兼容问题

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/InternLM#649]
### Describe the question.

测试基于 `chat-7b` 模型

**4.34/4.36（latest）**

```
pass
```
**4.31/4.32/4.33**
```
`demo`代码可运行，但输出中有 UNUSED_TOKEN_145 <|im_end|> 等
```
**4.30**

```
  File "/home/***/tmp_7b.py", line 10, in <module>
    model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-chat-7b", torch_dtype=torch.float16, token=access_token, trust_remote_code=True).cuda()
  File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: InternLM2ForCausalLM.__init__() got an unexpected keyword argument 'token'
```

**4.22**
```
[]$ python tmp_7b.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/home/***/tmp_7b.py", line 10, in <module>
    model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-chat-7b", torch_dtype=torch.float16, token=access_token, trust_remote_code=True).cuda()
  File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 237, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
```

**Comment by x54-729** [comment]
4.22 的报错和 transformers 的版本更新有关。在trust_remote_code=True 的情况下，transformers 会匹配加载文件中的 import 语句并且提前进行导入，而在不同版本中匹配的行为不一致：
在 transformers<4.27.0 中，transformers 会匹配所有 import 语句，在>=4.27.0时则会跳过使用try-except 导入的模块。
internlm2的模型为了支持 flash attention 使用了 try-except 语句导入 flash_attn 库，所以在较早版本的 transformers 中无法运行。

**Comment by x54-729** [comment]
4.30 的报错是因为用于登录的 token 参数在 transformers<4.31.0 中名称 use_auth_token，token 参数是 4.31.0之后才添加的，并且在几个版本后将会最终取代 use_auth_token；

**Comment by ZwwWayne** [comment]
那要不就卡下限卡到4.34？

**Comment by x54-729** [comment]
> 4.30 的报错是因为用于登录的 token 参数在 transformers<4.31.0 中名称 use_auth_token，token 参数是 4.31.0之后才添加的，并且在几个版本后将会最终取代 use_auth_token；

这个token参数基本上只是用于需要登录huggingface cli的情况，和我们的模型完全无关，可以在demo里去掉这个参数再测试下；4.33之前的版本我还在check

**Comment by del-zhenwu** [comment]
> > 4.30 的报错是因为用于登录的 token 参数在 transformers<4.31.0 中名称 use_auth_token，token 参数是 4.31.0之后才添加的，并且在几个版本后将会最终取代 use_auth_token；
> 
> 这个token参数基本上只是用于需要登录huggingface cli的情况，和我们的模型完全无关，可以在demo里去掉这个参数再测试下；4.33之前的版本我还在check

关注到了，我再试下

**Comment by del-zhenwu** [comment]
> 那要不就卡下限卡到4.34？

要不你们先确定这个，等后面兼容了再改？

**Comment by x54-729** [comment]
> > 那要不就卡下限卡到4.34？
> 
> 要不你们先确定这个，等后面兼容了再改？

我觉得可以

**Comment by zhulinJulia24** [comment]
我试了一下transformers=4.34.1和4.37.1版本，没法正常执行，报错

Traceback (most recent call last):
  File "/home/zhulin1/lmdeploy/autotest/transformers_func_regression_simple.py", line 32, in <module>
    fire.Fire(main)
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/zhulin1/lmdeploy/autotest/transformers_func_regression_simple.py", line 16, in main
    response, history = model.chat(tokenizer, "你好", history=[])
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhulin1/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b/modeling_internlm2.py", line 1168, in chat
    outputs = self.generate(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhulin1/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b/modeling_internlm2.py", line 1047, in forward
    outputs = self.model(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhulin1/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b/modeling_internlm2.py", line 890, in forward
    attention_mask = self._prepare_decoder_attention_mask(
  File "/home/zhulin1/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b/modeling_internlm2.py", line 814, in _prepare_decoder_attention_mask
    combined_attention_mask = _make_causal_mask(
  File "/home/zhulin1/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b/modeling_internlm2.py", line 88, in _make_causal_mask
    mask = torch.full((tgt_len, tgt_len), torch.tensor(torch.finfo(dtype).min, device=device), device=device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


使用demo的脚本，模型是internlm2-chat-20b

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import fire

def main(model_path: str):
    print ("start")
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    # `torch_dtype=torch.float16` 可以令模型以 float16 精度加载，否则 transformers 会将模型加载为 float32，导致显存不足
    model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.float16, trust_remote_code=True).cuda()
    model = model.eval()
    print ("end")

    for i in range(100):
        response, history = model.chat(tokenizer, "你好", history=[])
        print("single response:",response)
        # 你好！有什么我可以帮助你的吗？
        response, history = model.chat(tokenizer, "请提供三个管理时间的建议。", history=history)
        print("advance response:",response)


if __name__ == '__main__':
    fire.Fire(main)
```

**Comment by xiayouran** [comment]
> ### Describe the question.
> 测试基于 `chat-7b` 模型
> 
> **4.34/4.36（latest）**
> 
> ```
> pass
> ```
> 
> **4.31/4.32/4.33**
> 
> ```
> `demo`代码可运行，但输出中有 UNUSED_TOKEN_145 <|im_end|> 等
> ```
> 
> **4.30**
> 
> ```
>   File "/home/***/tmp_7b.py", line 10, in <module>
>     model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-chat-7b", torch_dtype=torch.float16, token=access_token, trust_remote_code=True).cuda()
>   File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
>     return model_class.from_pretrained(
>   File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
>     model = cls(config, *model_args, **model_kwargs)
> TypeError: InternLM2ForCausalLM.__init__() got an unexpected keyword argument 'token'
> ```
> 
> **4.22**
> 
> ```
> []$ python tmp_7b.py 
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
> Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
> Traceback (most recent call last):
>   File "/home/***/tmp_7b.py", line 10, in <module>
>     model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-chat-7b", torch_dtype=torch.float16, token=access_token, trust_remote_code=True).cuda()
>   File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
>     model_class = get_class_from_dynamic_module(
>   File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 363, in get_class_from_dynamic_module
>     final_module = get_cached_module_file(
>   File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 237, in get_cached_module_file
>     modules_needed = check_imports(resolved_module_file)
>   File "/home/***/df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
>     raise ImportError(
> ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
> ```

不错的工作！我在4.33.1版本中遇到了同样的问题，升级到4.34.0解决

**Comment by x54-729** [comment]
原因是 4.34.0之前的版本 transformers无法识别出tokenizer_config.json中的added_tokens_decoder，所以我们新添加的 <|im_start|> 并没有被加入到 tokenizer 中，在编码时会被分开
