### ISSUE TITLE
[Bug] AttributeError: module 'tokenizers.decoders' has no attribute 'Replace'

### ISSUE THREAD

**Issue by jiaoyang3** [InternLM/InternLM#655]
### Describe the bug

/Users/lambert/anaconda3/bin/python /Users/lambert/PycharmProjects/pythonProject/InternML/demo3.py 
Ignored unknown kwarg option byte_fallback
Traceback (most recent call last):
  File "/Users/lambert/PycharmProjects/pythonProject/InternML/demo3.py", line 3, in <module>
    tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-chat-7b", trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lambert/anaconda3/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 714, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lambert/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lambert/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lambert/.cache/huggingface/modules/transformers_modules/internlm/internlm2-chat-7b/1334f6269ff81eedf855ab13e4bdbe3c3d7ab3f4/tokenization_internlm2_fast.py", line 131, in __init__
    super().__init__(
  File "/Users/lambert/anaconda3/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lambert/anaconda3/lib/python3.11/site-packages/transformers/convert_slow_tokenizer.py", line 1332, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lambert/anaconda3/lib/python3.11/site-packages/transformers/convert_slow_tokenizer.py", line 540, in converted
    tokenizer.decoder = self.decoder(replacement, add_prefix_space)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lambert/.cache/huggingface/modules/transformers_modules/internlm/internlm2-chat-7b/1334f6269ff81eedf855ab13e4bdbe3c3d7ab3f4/tokenization_internlm2_fast.py", line 61, in decoder
    decoders.Replace("▁", " "),
    ^^^^^^^^^^^^^^^^
AttributeError: module 'tokenizers.decoders' has no attribute 'Replace'

Process finished with exit code 1

### Environment

Python 3.11.5

**Comment by x54-729** [comment]
What's the version of transformers? Updating transformers may works

**Comment by jiaoyang3** [comment]
> What's the version of transformers? Updating transformers may works

the latest version

4.37.1

**Comment by x54-729** [comment]
What's the version of `tokenizers`?
