### ISSUE TITLE
[Bug] ImportError:  InternLM2Converter requires the protobuf library

### ISSUE THREAD

**Issue by kkscilife** [InternLM/InternLM#656]
### Describe the bug

The more info about error:
```
Traceback (most recent call last):
  File "****/7b_sft.py", line 3, in <module>
    tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-chat-7b-sft", trust_remote_code=True)
  File "****/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "****/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "***/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "***/transformers_modules/internlm/internlm2-chat-7b-sft/e338c92d04a53077be140f238af5efe8f20d1a4d/tokenization_internlm2_fast.py", line 131, in __init__
    super().__init__(
  File "***/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "****/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1307, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "****/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 441, in __init__
    requires_backends(self, "protobuf")
  File "****/python3.10/site-packages/transformers/utils/import_utils.py", line 1014, in requires_backends
    raise ImportError("".join(failed))
ImportError: 
InternLM2Converter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
```
### Environment

python 3.10
transformers==4.30.2

**Comment by kkscilife** [comment]
I install protobuf, there is a new error:

File "/mnt/***/7b_sft.py", line 3, in <module>
    tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-chat-7b-sft", trust_remote_code=True)
  File "/mnt/***/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/mnt/***/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/mnt/petrelfs/qa-caif-cicd/env/anaconda3/envs/older-transformer-test/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/mnt/***/.cache/huggingface/modules/transformers_modules/internlm/internlm2-chat-7b-sft/e338c92d04a53077be140f238af5efe8f20d1a4d/tokenization_internlm2_fast.py", line 131, in __init__
    super().__init__(
  File "/mnt/***/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "/mnt/***/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 1307, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "/mnt/***/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 445, in __init__
    from .utils import sentencepiece_model_pb2 as model_pb2
  File "/mnt/***/python3.10/site-packages/transformers/utils/sentencepiece_model_pb2.py", line 91, in <module>
    _descriptor.EnumValueDescriptor(
  File "/mnt/***/python3.10/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 
Then I use version protobuf 3.20.3 and set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python, it keep hanging

**Comment by x54-729** [comment]
I'm sorry but I cannot regenerate this error in my environment.. what if try upgrade protobuf to 4.23.4?

**Comment by x54-729** [comment]
Also, if you don't need to process too much data for training, you can set `use_fast=False` to use slow tokenizer.

**Comment by kkscilife** [comment]
Thanks.
Now, I use protobuf 3.19.6, then it works

**Comment by hellocrystal** [comment]
socket.timeout: timed out
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm2_5-7b-chat/resolve/main/tf_model.h5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028E2CDC3340>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /internlm/internlm2_5-7b-chat/resolve/main/tf_model.h5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028E2CDC3340>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: c12744c4-670d-4484-9d02-d7f8ff417168)')
