### ISSUE TITLE
[Bug] 运行魔塔示例代码出现 AttributeError: 'ChatStreamer' object has no attribute 'cache'

### ISSUE THREAD

**Issue by tcexeexe** [InternLM/InternLM#668]
### 描述该错误

运行该页面中的流失接口示例代码出现报错：[书生·浦语2-对话-7B-SFT](https://modelscope.cn/models/Shanghai_AI_Laboratory/internlm2-chat-7b-sft/summary
```
Exception in thread Thread-2 (stream_producer):
Traceback (most recent call last):
  File "/home/tcexeexe/anaconda3/envs/internlm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tcexeexe/anaconda3/envs/internlm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tcexeexe/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b-sft/modeling_internlm2.py", line 1247, in stream_producer
    return self.chat(
  File "/home/tcexeexe/anaconda3/envs/internlm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tcexeexe/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b-sft/modeling_internlm2.py", line 1168, in chat
    outputs = self.generate(
  File "/home/tcexeexe/anaconda3/envs/internlm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/tcexeexe/anaconda3/envs/internlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1525, in generate
    return self.sample(
  File "/home/tcexeexe/anaconda3/envs/internlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2669, in sample
    streamer.put(next_tokens.cpu())
  File "/home/tcexeexe/.cache/huggingface/modules/transformers_modules/internlm2-chat-7b-sft/modeling_internlm2.py", line 1233, in put
    self.cache.extend(value.tolist())
AttributeError: 'ChatStreamer' object has no attribute 'cache'
```
示例代码如下：
```
from modelscope import snapshot_download, AutoTokenizer, AutoModelForCausalLM
import torch

model_dir = snapshot_download("Shanghai_AI_Laboratory/internlm2-chat-7b-sft")
tokenizer = AutoTokenizer.from_pretrained(model_dir, device_map="auto", trust_remote_code=True)
# Set `torch_dtype=torch.float16` to load model in float16, otherwise it will be loaded as float32 and might cause OOM Error.
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="auto",  trust_remote_code=True, torch_dtype=torch.float16)
model = model.eval()
length = 0
for response, history in model.stream_chat(tokenizer, "Hello", history=[]):
    print(response[length:], flush=True, end="")
    length = len(response)
```

### 环境信息

PyTorch 2.1.2
cuda 12.1
transformer 4.37

### 其他信息

是否是多卡环境下的问题，因为报错在线程2

**Comment by zhou762** [comment]
不是线程问题

**Comment by x54-729** [comment]
这是stream_chat 函数的bug；目前我们已经更新了代码，您可以更新下文件试试
