### ISSUE TITLE
[Bug] internlm2_5-20b-chat量化报错

### ISSUE THREAD

**Issue by maxin9966** [InternLM/InternLM#781]
### 描述该错误

lmdeploy lite auto_awq internlm/internlm2_5-20b-chat --work-dir /home/ma/work/models/internlm2_5-20b-chat-4bit --batch-size 8 --search-scale True

Move model.layers.45 to CPU.
Move model.layers.46 to CPU.
Move model.layers.47 to CPU.
Move model.norm to GPU.
Move output to CPU.
Loading calibrate dataset ...
The repository for ptb_text_only contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/ptb_text_only.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Traceback (most recent call last):
  File "/home/ma/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/lite.py", line 139, in auto_awq
    auto_awq(**kwargs)
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 105, in auto_awq
    vl_model, model, tokenizer, work_dir = calibrate(model,
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/apis/calibrate.py", line 213, in calibrate
    calib_loader, _ = get_calib_loaders(calib_dataset,
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/utils/calib_dataloader.py", line 302, in get_calib_loaders
    return get_ptb(tokenizer, nsamples, seed, seqlen)
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/lite/utils/calib_dataloader.py", line 58, in get_ptb
    traindata = load_dataset('ptb_text_only', 'penn_treebank', split='train')
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/datasets/load.py", line 2594, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/datasets/load.py", line 2266, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/datasets/load.py", line 1914, in dataset_module_factory
    raise e1 from None
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/datasets/load.py", line 1887, in dataset_module_factory
    ).get_module()
  File "/home/ma/miniconda3/envs/lmdeploy/lib/python3.10/site-packages/datasets/load.py", line 1538, in get_module
    raise ValueError(
ValueError: Loading ptb_text_only requires you to execute the dataset script in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

### 环境信息

Driver Version: 545.23.08    CUDA Version: 12.3

**Comment by AllentDan** [comment]
> Do you wish to run the custom code? [y/N]

Please input `y`.

**Comment by maxin9966** [comment]
@AllentDan I've seen this message, but when I tried it several times, it directly showed an error. There was no step where I had to input 'y'.
