### ISSUE TITLE
[Bug] Unable to run inference using internlm/internlm2_5-7b-chat-4bit

### ISSUE THREAD

**Issue by LanHikari22** [InternLM/InternLM#785]
### Describe the bug

The README specifies that we can run inference on `internlm/internlm2_5-7b-chat-4bit ` with the following code: 
```python
from lmdeploy import pipeline
pipe = pipeline("internlm/internlm2_5-7b-chat-4bit")
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)
```
However, when I run this code to reproduce a correct inference I get the following:

```
Traceback (most recent call last):
  File "/media/lan/0E9EEB179EEAF5DD/lan-proart/src/exp/ex/internLM/lmdeploy-script-1/deploy-7b-4bit.py", line 2, in <module>
    pipe = pipeline("internlm/internlm2_5-7b-chat-4bit")
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/api.py", line 62, in pipeline
    return AsyncEngine(model_path,
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 68, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 145, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 195, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 312, in _from_hf
    output_model = OUTPUT_MODELS.get(output_format)(
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 26, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 141, in __init__
    self.cfg = self.get_config(cfg)
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 38, in get_config
    w1, _, _ = bin.ffn(i)
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/internlm2.py", line 64, in ffn
    return self._ffn(i, 'weight')
  File "/home/lan/miniconda3/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/internlm2.py", line 58, in _ffn
    tensor = self.params[f'model.layers.{i}.feed_forward.{key}.{kind}']
KeyError: 'model.layers.0.feed_forward.w1.weight'

```

#### CUDA Version
```bash
nvcc --version
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
```

#### Tensorflow Version

```python
import tensorflow as tf
print(tf.__version__)
```

```
2024-08-06 16:28:07.191975: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-06 16:28:07.444359: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-06 16:28:08.420463: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> print(tf.__version__)
2.12.0
```

#### PyTorch Version and Related Information
```python
import torch
print("torch version:", torch.__version__)
print("torch cuda version:", torch.version.cuda)
print("torch cuda available:", torch.cuda.is_available())
print("torch device count:", torch.cuda.device_count())
if torch.cuda.is_available():
    for i in range(torch.cuda.device_count()):
        print(f"GPU {i}: {torch.cuda.get_device_name(i)}")
```

```
torch version: 2.1.1+cu121
torch cuda version: 12.1
torch cuda available: True
torch device count: 1
GPU 0: NVIDIA TITAN RTX
```

#### Transformers Version
```python
import transformers
print(transformers._version__)
```

```
4.42.0
```

Installed via
```
python3 -m pip install git+https://github.com/huggingface/transformers
```

#### Python Version
```python
import sys
print(sys.version)
print(sys.executable)
```

```
3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
/home/lan/miniconda3/bin/python3
```

```bash
conda --version
```

```
conda 23.11.0
```

### Other information

1. Did you make any modifications on the code or config?

I reproduce the issue with the minimal example provided. I did not modify the code driving the example.

2. What do you think might be the reason?

I found a related issue https://github.com/InternLM/lmdeploy/issues/1500 that had a similar error, but this was fixed in May.

I have also tried to set the quant_policy as suggested in the README, but that still reproduced the issue.
```py
from lmdeploy import pipeline, TurbomindEngineConfig
pipe = pipeline("internlm/internlm2_5-7b-chat-4bit",
                backend_config=TurbomindEngineConfig(quant_policy=8))
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)
```

**Comment by zhulinJulia24** [comment]
@LanHikari22 hi, please use demo code in https://huggingface.co/internlm/internlm2_5-7b-chat-4bit 
need add model_format='awq' into TurbomindEngineConfig config becuase this is a 4bit quantization model.

**Comment by LanHikari22** [comment]
@zhulinJulia24 Hi. Thanks for the help, I am able to run the 4-bit quantization now, but I am still having issues with the result quality. I have also noticed this happened with full 7B inference. I do not get a CUDA out of memory error, but I do get gibberish output. When I run 1.8B, I am able to get sensible output.

Please see the following as to how I reproduce the issue:

```python
from lmdeploy import pipeline, TurbomindEngineConfig

engine_config = TurbomindEngineConfig(model_format='awq')

pipe = pipeline("internlm/internlm2_5-7b-chat-4bit", backend_config=engine_config)

question = 'What is 1+1?'
print('question', question)

response = pipe(question)
print(response)
```

```
(base) lmdeploy-script-1 ➜ python3 deploy-7b-4bit.py        
Fetching 14 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 94254.02it/s]
[WARNING] gemm_config.in is not found; using default GEMM algo                                                                                                                                                     
question What is 1+1?
Response(text='1,p,p -araaraara -usoPLY＞＞araZip＞ ConPLY＞＞ara＞＞,p＞araPLY＞ becomingPLYara＞araara Conara＞-Zipopa＞ara＞＞ara＞Zip -ara＞PLYarausoara becoming主动＞arausoaraaho行动主动＞行动ara -＞,p becoming,para＞死 -＞usoPLYara＞＞opa＞-acesaraara＞＞＞＞＞araara＞usoaraZip行动 -死ara＞＞＞死嫌 For -主动＞＞ara -araZip＞ becoming＞行动araZipara For,p -ara＞araaraara For＞＞＞opa -＞＞＞主动uso＞ -行动araaraara行动arauso -araZip＞＞ -主动主动行动 - -araopaarausoara＞主动主动 -Ziparaara,pahoara＞＞＞＞araopa＞araaces-y Foruso Conuso主动acesuso＞＞usoZiparaara - becomingaraaraaraarauso＞＞uso becomingaces＞araarauso行
动 -acesuso＞主动araarausouso嫌aces嫌ara＞ara becomingaho＞ -uso＞ -PLY becomingara-y＞嫌-＞,paho becoming-yaraaraara -＞ara主动acesusoara -ara＞＞usoaraaho-yZip＞uso -Zipopaaraaraara,p＞＞ara＞ -uso＞ -＞araZipZipara嫌 - -araaraaraZipopa＞嫌 -行动＞ -主动acesaraara＞＞-y Con＞＞aces,paraara becomingara Forara＞＞ For＞ara＞,p＞Zipuso主动araopa＞ara -PLY＞ ConarausoPLY＞acesusoopa＞＞ becomingaraaraara-usoZip -,p＞＞,p
＞主动主动aces＞,pusoara＞usoaho-＞araZiparaopa -uso For,p For becoming主动araara嫌 For Con＞araara＞-y becoming,p＞ara＞ara＞行动＞aces＞主动uso行动usoZip becoming -主动ara-ara -aces -arausoacesara＞araara主动
主动嫌 becomingaho＞-y＞ -aces＞ara becoming＞ara＞ -＞主动Zip主动ara -＞ becoming - --y＞＞-ara -ara,para -＞嫌ara主动＞usoZip＞ -- - -PLY＞＞ becoming死araaraaces行动主动ara -＞ara＞aces becoming主动uso＞arausoahoZip -ara行动＞ara Conahoaraaraacesara', generate_token_len=513, input_token_len=8, session_id=0, finish_reason='length')
```
21262MiB / 24576MiB VRAM are allocated from my GPU during this process.

I similarly reproduce gibberish when I replicate MindSearch's inference setup:

```python
from lagent.llms import INTERNLM2_META, LMDeployServer
from lmdeploy import TurbomindEngineConfig
import random


engine_config = TurbomindEngineConfig(model_format='awq')

internlm_server_cfg = dict(
                       path='internlm/internlm2_5-7b-chat-4bit',
                       model_name='internlm2',
                       meta_template=INTERNLM2_META,
                       serve_cfg={'backend_config': engine_config},
                       top_p=0.8,
                       top_k=1,
                       temperature=0,
                       max_new_tokens=8192,
                       repetition_penalty=1.02,
                       stop_words=['<|im_end|>'])

llm = LMDeployServer(**internlm_server_cfg)

prompt = 'Hi. What is 1+1?'
print('prompt', prompt)

print('--- Beginning Stream ---')

for model_state, response, _ in llm.stream_chat(prompt, session_id=random.randint(0, 999999)):
    print(f'model_state: {model_state}, response: {response}, _: {_}')

print('--- Done ---')
```

```
(base) lmdeploy-script-1 ➜ python3 deploy-7b-4bit-mindsearch-setup.py                                                                                                                                              
2024-08-07 19:20:29,214 - lmdeploy - WARNING - model_source: hf_model                             
Fetching 14 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 152520.15it/s]
2024-08-07 19:20:32,337 - lmdeploy - WARNING - model_config:
                                                                                                                                                                                                                   
[llama]                                                                                                  
model_name = internlm2                                                                                   
tensor_para_size = 1               
head_num = 32                                                                                            
kv_head_num = 8                                                                                          
vocab_size = 92544                                                                                       
num_layer = 32                                                                                           
inter_size = 14336                                                                                                                                                                                                 
norm_eps = 1e-05               
attn_bias = 0                                                                                                                                                                                                      
start_id = 1                                                                                             
end_id = 2                                                                                               
session_len = 32768               
weight_type = int4
rotary_embedding = 128 
rope_theta = 1000000.0                     
size_per_head = 128                     
group_size = 128                          
max_batch_size = 128
max_context_token_num = 1  
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 32768
rope_scaling_factor = 0.0
use_logn_attn = 0


[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 32768.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (32768).
2024-08-07 19:20:32,483 - lmdeploy - WARNING - get 355 model params
[WARNING] gemm_config.in is not found; using default GEMM algo                                                                                                                                                     
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
INFO:     Started server process [825969]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)
INFO:     127.0.0.1:60036 - "GET /v1/models HTTP/1.1" 200 OK
Launched the api_server in process 825969, user can kill the server by:
import os,signal
os.kill(825969, signal.SIGKILL)
prompt Hi. What is 1+1?
--- Beginning Stream ---
INFO:     127.0.0.1:60040 - "POST /v1/completions HTTP/1.1" 200 OK
[TM][WARNING] [ProcessInferRequests] Request for 526950 received.
model_state: 1, response:  , _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None
model_state: 1, response:  挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战挑战, _: None

...

“接着我们提供, by中木偶
“接着我们提供, by中木偶
“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们提供，出生於上海到：左下角的下转 性的，本答案
“接着我们提供，本答案
“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些“接着我们不。有哪些，本答案
“接着我们提供, _: None
--- Done ---
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [832807]
```

VRAM Use here is similarly 21262MiB / 24576MiB.

Please advise on possible causes and solutions for this issue.

Thank you!
Lan
