### ISSUE TITLE
[QA] 我按照官方文档的步骤，尝试调用书生浦语的API来回答问题，但是报错：模型已下架

### ISSUE THREAD

**Issue by atpdxy** [InternLM/InternLM#788]
### Describe the question.

from log import setup_logger
from openai import OpenAI

logger = setup_logger(__name__)

client = OpenAI(
    api_key="",
    base_url="https://internlm-chat.intern-ai.org.cn/puyu/api/v1/",
)

chat_rsp = client.chat.completions.create(
    model="internlm2-latest",
    messages=[{"role": "user", "content": "hello"}],
)

for choice in chat_rsp.choices:
    print(choice.message.content)

报错信息如下：
Traceback (most recent call last):
  File "E:\langchain_test\langchain_shusheng\api.py", line 12, in <module>
    chat_rsp = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atpdx\.conda\envs\langchain_maas\Lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atpdx\.conda\envs\langchain_maas\Lib\site-packages\openai\resources\chat\completions.py", line 668, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\atpdx\.conda\envs\langchain_maas\Lib\site-packages\openai\_base_client.py", line 1259, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\atpdx\.conda\envs\langchain_maas\Lib\site-packages\openai\_base_client.py", line 936, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\atpdx\.conda\envs\langchain_maas\Lib\site-packages\openai\_base_client.py", line 1040, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'code': -20013, 'msg': '模型已下架，请新开会话', 'traceId': '53c488e226b2bfb1b1f8925b0a89ebe6', 'data': {'id': '', 'object': 'chat.completion', 'model': 'internlm2', 'created': 1723511327, 'choices': [{'index': 0, 'finish_reason': ''}], 'moderation': {'sensitive': False, 'category': ''}}}

**Comment by flyhighzy** [comment]
model名称可能会不定期更新为新版本，代表着实际的部署版本也已经被更新。一般小版本model name不会变化，大版本更新时旧版本可能会下线。建议遇到类似问题先调用model list接口查看可用model name~
